"""Add full_name to user table

Revision ID: 4817efd2a8d7
Revises: 
Create Date: 2025-07-29 11:51:43.980051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4817efd2a8d7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('assigned_to',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_ticket_assigned_to_user', 'user', ['assigned_to'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_assigned_to_user', type_='foreignkey')
        batch_op.alter_column('assigned_to',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)


    # ### end Alembic commands ###
